project:
  title: "plain-text-statistician"
  type: website

website:
  favicon: images/favicon.png

format:
  html:
    theme: [default, custom.scss]
    mainfont: "Libre Franklin, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Noto Sans, Liberation Sans, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji"
